language: bash

sudo: required

services:
- docker

branches:
  only:
  - master

before_install:
  - 'if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then
       IMAGE_NAME=kawashironitori/docker-wine-coolq:mr-$TRAVIS_PULL_REQUEST
     else
       IMAGE_NAME=kawashironitori/docker-wine-coolq:latest
     fi'

install:
- docker build -t $IMAGE_NAME .

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker push $IMAGE_NAME
