#!/usr/bin/with-contenv /bin/bash
hasexe=$(find /home/user/coolq -maxdepth 1 -type f -name '*.exe')
if [ "$hasexe" != "" ] ; then
    echo 'CoolQ already exists, skip download.'
else
    echo 'Downloading CoolQ ...'
    mkdir /tmp/cq
    wget $COOLQ_URL -O /tmp/cq/coolq.zip
    echo 'Unzipping CoolQ ...'
    cd /tmp/cq
    LC_ALL=zh_CN.UTF-8 unzip coolq.zip > /dev/null
    mv */* /home/user/coolq
    chown -R user:user /home/user/coolq
    rm -rf /tmp/cq
fi